### ISSUE TITLE
[REQUEST] Change "Playing iTunes" in Discord to "Playing Apple Music"

### ISSUE THREAD

**Issue by Geode1010** [kevinmussi/iTunes-Discord-RP#13]

**Comment by kevinmussi** [comment]
I think I can do that by simply changing the name of the Discord application I use to send the rich presence data, but maybe just "Music" could be better? I'd like to get more opinions on this though.

**Comment by Geode1010** [comment]
You could just add a text box to the app where you can edit it with the default being "iTunes"

**Comment by kevinmussi** [comment]
You can't do it like that, the name it shows is the name of my Discord app.

**Comment by Charmandrigo** [comment]
I would recommend using the apple emoji for a better look
example: "Music"

**Comment by zllovesuki** [comment]
@kevinmussi now I'm curious. I changed the `description` in the ITUNES enum under Application.java, and it still shows up as "iTunes". Am I looking at the wrong place? (I did repackage it in maven)

**Comment by kevinmussi** [comment]
The name that shows is the name of the Discord application that the Java program connects to, in this case it's an ad-hoc application that I called "iTunes", so that it shows that name. I guess you could create your own Discord application and put its ID in [DiscordHelper.java](https://github.com/kevinmussi/iTunes-Discord-RP/blob/master/src/main/java/com/github/kevinmussi/itunesrp/core/DiscordHelper.java) (variable `APP_ID`), but that would also make the images not show up anymore (since those are loaded from the Discord application you link).

Anyway, I think for now I'll change it to "Music", since "Playing Music" makes the most sense to me and it's valid both for iTunes and Music app.
