### ISSUE TITLE
[Request] Making status appearance customizable

### ISSUE THREAD

**Issue by Enigmanotta** [kevinmussi/iTunes-Discord-RP#3]
Hello,

I'd like to know if it would be possible for you to make an option where we could customize the appearance of the status? I'd like to be able to remove the album and (X out of Y) informations or to move them below the artist's name and above the timer.

I don't know anything about coding so please forgive me if that's impossible to do.

Also, you're the only great and convenient app I found working under macOS so thank you for that!

**Comment by kevinmussi** [comment]
Hi!
The Discord status elements are set (the timer is always at the bottom, the (X out of Y) is always at the end of the penultimate line and you can't have more than two lines below the game name), but still it could be possible to make the user move the elements around or disable some of them (or even show the song's name instead of "iTunes" as currently playing game). I'll definitely do that in the next update!

**Comment by thatJARED** [comment]
To add onto this. 
The emojis to decipher the different information are a little bit clunky. Maybe an option to disable them. I love the suggestion of moving the different info around. Maybe having the artist and song on one line and the album on the other. 

![screen shot 2019-02-01 at 7 47 00 pm](https://user-images.githubusercontent.com/17349406/52115664-e9a00000-265a-11e9-9b38-edd58e7d8dd3.png

I love the fact that you are putting effort into this though my man! Keep it up. 😃

**Comment by kevinmussi** [comment]
The [latest release](https://github.com/kevinmussi/iTunes-Discord-RP/releases/latest) added options for both issues addressed here: enable or disable emojis, and change where the artist and album fields are located (or remove them). I'm sorry this took so long to add!
