### ISSUE TITLE
Album artwork

### ISSUE THREAD

**Issue by eloyaldea** [kevinmussi/iTunes-Discord-RP#6]
Hi, just found this app because I don't use Spotify so this is great! Just if the album artwork could be displayed as well as the title, album, etc.
Also if it could be a background app in the menu bar instead of the dock would be great :D.
Keep the good work!

**Comment by kevinmussi** [comment]
Hi, sadly the public Discord RPC API doesn't allow to dinamically change the displayed picture, so I had to stick with a bland iTunes logo.
When I have time to work on this I will make the app a menu bar app (if it's possible with Java).

**Comment by Charmandrigo** [comment]
Isn't it possible with this? 
https://discordapp.com/developers/docs/rich-presence/best-practices#have-interesting-expressive-art

**Comment by domingosc6** [comment]
> Isn't it possible with this?
> https://discordapp.com/developers/docs/rich-presence/best-practices#have-interesting-expressive-art

It would be really nice if this gets album artwork! Commenting to "up" this.

**Comment by kevinmussi** [comment]
> Isn't it possible with this?
https://discordapp.com/developers/docs/rich-presence/best-practices#have-interesting-expressive-art

No, that's how I show the iTunes logo in the first place, but I can't use that to show the current artwork, because I can't load the image at runtime (you can only set certain pictures before and then use those). Spotify is able to do that because they probably use a different API, which isn't accessible for other applications.
